name: neuralforecast
channels:
  - conda-forge
  - pytorch
dependencies:
  - jupyterlab
  - matplotlib
  - numpy>=1.21.6
  - pandas>=1.3.5
  - pytorch>=2.0.0
  - pytorch-lightning>=2.0.0
  - scipy<1.11.2
  - pip
  - pip:
    - nbdev
    - black
    - hyperopt
    - "ray[tune]>=2.2.0"
    - tensorboardx<2.6.2
    - click<8.1.7
