version: 2.1
jobs:
  nbdev-tests:
    resource_class: xlarge
    docker:
      - image: continuumio/miniconda3:23.3.1-0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt update -y && apt upgrade -y
            conda install mamba -n base -c conda-forge
            mamba create -n neuralforecast python=3.8
            conda init bash
            source ~/.bashrc
            conda activate neuralforecast
            mamba env update -f environment.yml
      - run:
          name: Run nbdev tests
          command: |
            conda init bash
            source ~/.bashrc
            conda activate neuralforecast
            pip install ./
            python -c "import pandas as pd;"
            nbdev_test --do_print --timing --n_workers 1
  test-model-performance:
    resource_class: xlarge
    docker:
      - image: continuumio/miniconda3:23.3.1-0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            conda install mamba -n base -c conda-forge
            conda create -n neuralforecast python=3.8
            conda init bash
            source ~/.bashrc
            conda activate neuralforecast
            mamba env update -f environment.yml
            python -c "import pandas as pd;"
            pip install ./
            python -c "import pandas as pd;"
            cd ./action_files/test_models/
            python -c "import pandas as pd;"
            pip install -r requirements.txt
            cd ../../
      - run:
          name: Run model performance tests
          command: |
            conda init bash
            source ~/.bashrc
            conda activate neuralforecast
            python -c "import pandas as pd;"
            cd ./action_files/test_models/
            python3 -m src.models
            python3 -m src.evaluation
            cd ../../
      - store_artifacts:
          path: ./action_files/test_models/data/evaluation.csv
          destination: evaluation.csv

workflows:
  sample:
    jobs:
      - nbdev-tests
      - test-model-performance
